type: depth_anything_v2
name: depth_anything_v2_vit_b-r20240721
display_name: Depth Anything V2 (ViT-Base)
model_path:
  local: F:\Github\X-AnyLabeling\weights\dam\depth_anything_v2_vitb.onnx
  online: https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.4.0/depth_anything_v2_vitb.onnx
render_mode: color
