type: grounding_sam2
name: groundingdino_swint_sam2_large-r20240806
display_name: GroundingSAM2
model_type: groundingdino_swint_ogc
model_path:
  local: F:\Github\X-AnyLabeling\weights\dino\groundingdino_swint_ogc_quant.onnx
  online: https://github.com/CVHub520/X-AnyLabeling/releases/download/v1.0.0/groundingdino_swint_ogc_quant.onnx
input_width: 1200
input_height: 800
box_threshold: 0.3
text_threshold: 0.25
encoder_model_path:
  local: F:\Github\X-AnyLabeling\weights\sam2\sam2_hiera_large.encoder.onnx
  online: https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.4.0/sam2_hiera_large.encoder.onnx
decoder_model_path:
  local: F:\Github\X-AnyLabeling\weights\sam2\sam2_hiera_large.decoder.onnx
  online: https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.4.0/sam2_hiera_large.decoder.onnx
