type: segment_anything_2
name: sam2_hiera_tiny-r20240801
display_name: Segment Anything 2 (Tiny)
encoder_model_path:
  local: F:\Github\X-AnyLabeling\weights\sam2\sam2_hiera_tiny.encoder.onnx
  online: https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.4.0/sam2_hiera_tiny.encoder.onnx
decoder_model_path:
  local: F:\Github\X-AnyLabeling\weights\sam2\sam2_hiera_tiny.decoder.onnx
  online: https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.4.0/sam2_hiera_tiny.decoder.onnx
