type: segment_anything_2
name: sam2_hiera_large-r20240801
display_name: Segment Anything 2 (Large)
encoder_model_path:
  local: F:\Github\X-AnyLabeling\weights\sam2\sam2_hiera_large.encoder.onnx
  online: https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.4.0/sam2_hiera_large.encoder.onnx
decoder_model_path:
  local: F:\Github\X-AnyLabeling\weights\sam2\sam2_hiera_large.decoder.onnx
  online: https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.4.0/sam2_hiera_large.decoder.onnx
