type: yolov8_obb_track
name: yolov8n_obb_botsort-r20240816
display_name: YOLOv8n-Obb-BoT-SORT
model_path:
  local: null
  online: https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.4.0/yolov8n_obb_car_bus.onnx
nms_threshold: 0.5
confidence_threshold: 0.1
tracker:
  tracker_type: botsort
  track_high_thresh: 0.5
  track_low_thresh: 0.1
  new_track_thresh: 0.6
  track_buffer: 30
  match_thresh: 0.8
  fuse_score: true
  gmc_method: sparseOptFlow
  proximity_thresh: 0.5
  appearance_thresh: 0.25
  with_reid: false
classes:
- car
- bus
