type: ram
name: ram_swin_large_14m-r20231024
display_name: RAM (SwinL) OPPO
model_path:
  local: E:\models\Xlabel\ram\ram_swin_large_14m.onnx
  online: https://github.com/CVHub520/X-AnyLabeling/releases/download/v1.0.0/ram_swin_large_14m.onnx
